### ISSUE TITLE
Use "positive" variable names

### ISSUE THREAD

**Issue by mayisa87** [ScribblesUrsa/Slot-Machine#10]
https://github.com/ScribblesUrsa/Slot-Machine/blob/970231c4992f27bf2b7801636c321ac480dd61ef/Program.cs#L202

Instead of naming variables something like notXY you could think about positive variable names. Hard to describe 😅
Examples:
Instead of notValid isValid
notRightPosition / isRightPosition

So in your case, notQuadribleWin, as you set it only in case of Jackpot, the varible could be isJackpot, or jackpotWon

It is easier to read it this way, somthing psychological I think 😅

**Comment by ScribblesUrsa** [comment]
I think I removed the negative ones now :)

**Comment by mayisa87** [comment]
Recently when searching for something else, I found this webpage that explains a bit better (than me ;) ) why negative naming of variables is not the best you can do ;)

https://levelup.gitconnected.com/knot-of-nots-avoiding-negative-names-for-boolean-methods-641896a94a42#:~:text=The%20usual%20convention%20to%20name,exists().
