### ISSUE TITLE
Use constants

### ISSUE THREAD

**Issue by mayisa87** [ScribblesUrsa/Slot-Machine#13]
https://github.com/ScribblesUrsa/Slot-Machine/blob/46fd7c6c6a76350adbf62d31ed4bceb47681c000/Program.cs#L192
https://github.com/ScribblesUrsa/Slot-Machine/blob/46fd7c6c6a76350adbf62d31ed4bceb47681c000/Program.cs#L211
https://github.com/ScribblesUrsa/Slot-Machine/blob/46fd7c6c6a76350adbf62d31ed4bceb47681c000/Program.cs#L218

Define constants for 0, 1 and 2 and use it in your code then.

**Comment by ScribblesUrsa** [comment]
Hello. Is it still advisable to declare them as constants? I get the red squigglies when I do const right by it.

**Comment by mayisa87** [comment]
ou often use line count 2 or line count 1 to check how many winning lines you got. 
You could use a constant like DOUBLE_LINES_WIN or SINGLE_LINE_WIN and use it in your if like :

if ((lineDiagonalWinCount == DOUBLE_LINES_WIN  || lineHorizontalWinCount == DOUBLE_LINES_WIN  || lineVerticalWinCount == DOUBLE_LINES_WIN 
) && !notQuadrupleLineWin)
