### ISSUE TITLE
Lot of variables....

### ISSUE THREAD

**Issue by mayisa87** [ScribblesUrsa/Slot-Machine#6]
https://github.com/ScribblesUrsa/Slot-Machine/blob/970231c4992f27bf2b7801636c321ac480dd61ef/Program.cs#L67-L73

I think this part is to reset all of your variables?
Having so much variables is really confusing to read. You could only define two variables like
int lineWinningCheck  (or better lineMatchingValueCount) and int lineWinCount and use them in all cases, vertical horizontal and diagonal. So you can reset it always to 0 before checking next line type. 

Would make the code better readable

**Comment by mayisa87** [comment]
But as I looked at your code more closely, I'm not sure if you can have less variables, as your winning conditions are build up on them. So this is maybe depending on, how your game logic really works, for me the game rules or winning conditions are not yet 100% clear. See my messages and questions in WA. 

[11:23, 11.9.2023] Isabella: And... I just trying to understand the winning logic. 
So the Jackpot is, 3 lines, of same direction? So all 3 horizontal, all vertical? Or doesn't matter which combination?
So why is 3 lines the Jackpot? Winning 4 lines will give you more win or?
[13:54, 11.9.2023] Isabella: Pointing to the curent implementation, the winning conditions are:
1.) If 1  line in any direction hor/Vert/diag matches
2.) if 2 lines in any direction hor/vert/dia match
3.) 2 lines in all directions hor/vert/dia match
4.) Or Jackpot: If all 3 horizontal lines match

Did I sum it up right? Because your entrance message is a bit misleading then, you write there:
""Four lines of the same characters of any direction wins you "

if 1-2 should be, the sum of winning lines doesn't matter in which direction, I think issue 6 on GitHub is something you should have a look to ;)

**Comment by mayisa87** [comment]
So, after I got all information about the game logic now, I had a closer look on it again. You will need the variables for the amount of lines won for each line type, like lineVerticalWinCount. As those variables are checked later in your winning conditions.

But variables like diagonalWinningCheck can be defined in the loop directly, as you only need it there. Or at least directly before the loops where it is needed, to make code better readable.

**Comment by mayisa87** [comment]
Next step would be to not define all variables at the same place, there is a HUGE amount of variables that are all defined before the while loop, what for? Better define it where you need it. 

First thing you need to take care about, variables are NOT AUTOMATICALLY UPDATED!

https://github.com/ScribblesUrsa/Slot-Machine/blob/38a2f942b3201e35b91cac4c924e5095d3558fdc/Program.cs#L39-L42
So you define this winning boolean flags outside of the while loop, and according on the actual value of the variables, they will be true or false, but if you do not update those values in your while loop, it won't work.

So a better place where to put those variable definitions would be, directly before your winning checks, like on line 195 or something like that.


======================= LINE COUNTS ======================
Let's have a look to one of the variables to count the winning lines. Like lineHorizontalWinCount

**Comment by ScribblesUrsa** [comment]
Note to self. SCOPE lol
